"""Factory simulator — replays generated sensor data as a live Kafka stream.

Data source priority:
  1. data/sensor_readings.json  — generated by datagen CLI
  2. ClickHouse sensor_readings  — last 24 h, used if JSON file absent
"""

import argparse
import logging
import random
import time
import uuid
from collections import defaultdict
from datetime import datetime
from pathlib import Path

from src.datagen.factory_model import FACTORY_MACHINES, FACTORY_STATIONS
from src.streaming.producer import flush, publish_production_event, publish_sensor_reading
from src.streaming.topics import ProductionEventMessage, SensorMessage

logger = logging.getLogger("primeev.streaming.simulator")

_STATION_IDS = list(FACTORY_STATIONS.keys()) if FACTORY_STATIONS else []


def _load_from_json(data_dir: str) -> list[dict]:
    """Load sensor readings from the datagen JSON export."""
    sensor_file = Path(data_dir) / "sensor_readings.json"
    if not sensor_file.exists():
        return []
    logger.info("Loading sensor data from %s ...", sensor_file)
    import json
    with open(sensor_file) as f:
        readings = json.load(f)
    logger.info("Loaded %d readings from JSON", len(readings))
    return readings


def _load_from_clickhouse(limit: int = 100_000) -> list[dict]:
    """Fall back to ClickHouse when the JSON file is absent."""
    logger.info("JSON file not found — querying ClickHouse for last 24 h of sensor data ...")
    try:
        from src.db.clickhouse.client import query
        rows = query(f"""
            SELECT
                formatDateTime(timestamp, '%Y-%m-%dT%H:%i:%S') AS timestamp,
                machine_id,
                station_id,
                sensor_type,
                value,
                unit
            FROM primeev_telemetry.sensor_readings
            WHERE timestamp >= (
                SELECT max(timestamp) FROM primeev_telemetry.sensor_readings
            ) - INTERVAL 1 DAY
            ORDER BY timestamp
            LIMIT {limit}
        """)
        logger.info("Loaded %d readings from ClickHouse", len(rows))
        return rows
    except Exception as exc:
        logger.error("ClickHouse fallback failed: %s", exc)
        return []


def _emit_shift_change(station_ids: list[str]) -> None:
    """Publish a shift_change production event for every station at startup."""
    hour = datetime.now().hour
    if 6 <= hour < 14:
        shift = "Day"
    elif 14 <= hour < 22:
        shift = "Swing"
    else:
        shift = "Night"

    for station_id in station_ids:
        msg = ProductionEventMessage(
            event_type="shift_change",
            station_id=station_id,
            status=shift,
            timestamp=datetime.now().isoformat(),
        )
        publish_production_event(msg)
    logger.info("Published shift_change (%s) for %d stations", shift, len(station_ids))


def _emit_batch_start(station_id: str, batch_id: str, model_id: str) -> None:
    """Publish a batch_start production event for the given station and batch."""
    publish_production_event(ProductionEventMessage(
        event_type="batch_start",
        station_id=station_id,
        batch_id=batch_id,
        model_id=model_id,
        status="running",
        timestamp=datetime.now().isoformat(),
    ))


def _emit_batch_end(station_id: str, batch_id: str) -> None:
    """Publish a batch_end production event marking a completed batch at the given station."""
    publish_production_event(ProductionEventMessage(
        event_type="batch_end",
        station_id=station_id,
        batch_id=batch_id,
        status="completed",
        timestamp=datetime.now().isoformat(),
    ))


def run_simulator(
    data_dir: str = "data",
    speed_multiplier: float = 100.0,
    max_messages: int | None = None,
    emit_production_events: bool = True,
) -> None:
    """Replay sensor data as a live Kafka stream with production events interleaved.

    Args:
        data_dir: Directory containing generated JSON data files.
        speed_multiplier: Playback speed (1.0 = real-time, 0 = as fast as possible).
        max_messages: Stop after this many sensor messages.
        emit_production_events: Publish shift_change and batch events alongside sensor data.
    """
    readings = _load_from_json(data_dir) or _load_from_clickhouse()
    if not readings:
        logger.error("No sensor data available. Run 'python -m src.datagen.cli generate' first.")
        return

    station_ids = list({r.get("station_id", "") for r in readings if r.get("station_id")})

    # Emit shift change at startup so the consumer/frontend knows the current shift
    if emit_production_events and station_ids:
        _emit_shift_change(station_ids)

    # Track active batches per station for batch start/end events
    # Simple heuristic: rotate batch ID every ~500 sensor messages per station
    batch_counters: dict[str, int] = defaultdict(int)
    active_batches: dict[str, str] = {}
    _BATCH_ROTATE_EVERY = 500

    message_count = 0
    last_ts: str | None = None
    start_time = time.time()

    logger.info(
        "Simulator starting: %d readings, speed=%.1fx, max=%s",
        len(readings), speed_multiplier, max_messages or "unlimited",
    )

    try:
        for reading in readings:
            station_id = reading.get("station_id", "")

            # ── Batch event rotation ──────────────────────────────────────────
            if emit_production_events and station_id:
                batch_counters[station_id] += 1
                if batch_counters[station_id] % _BATCH_ROTATE_EVERY == 1:
                    # End previous batch if one is active
                    if station_id in active_batches:
                        _emit_batch_end(station_id, active_batches[station_id])

                    # Start a new batch
                    model_choices = ["PE-SD100", "PE-SV200", "PE-CP300"]
                    new_batch_id = f"BATCH-{uuid.uuid4().hex[:8].upper()}"
                    new_model = random.choice(model_choices)
                    active_batches[station_id] = new_batch_id
                    _emit_batch_start(station_id, new_batch_id, new_model)

            # ── Sensor reading ────────────────────────────────────────────────
            msg = SensorMessage(
                machine_id=reading.get("machine_id", ""),
                station_id=station_id,
                sensor_type=reading.get("sensor_type", ""),
                value=float(reading.get("value", 0.0)),
                unit=reading.get("unit", ""),
                timestamp=reading.get("timestamp", datetime.now().isoformat()),
            )
            publish_sensor_reading(msg)
            message_count += 1

            # ── Throttle ──────────────────────────────────────────────────────
            current_ts = reading.get("timestamp")
            if speed_multiplier > 0 and last_ts and current_ts:
                try:
                    delta = (
                        datetime.fromisoformat(str(current_ts))
                        - datetime.fromisoformat(str(last_ts))
                    ).total_seconds()
                    if delta > 0:
                        time.sleep(delta / speed_multiplier)
                except (ValueError, TypeError):
                    pass
            last_ts = current_ts

            if message_count % 1000 == 0:
                flush(timeout=2.0)
                elapsed = time.time() - start_time
                rate = message_count / elapsed if elapsed > 0 else 0
                logger.info("Published %d messages (%.0f msg/s)", message_count, rate)

            if max_messages and message_count >= max_messages:
                break

    except KeyboardInterrupt:
        logger.info("Simulator interrupted")
    finally:
        # Close any open batches
        if emit_production_events:
            for station_id, batch_id in active_batches.items():
                _emit_batch_end(station_id, batch_id)

        remaining = flush(timeout=10.0)
        elapsed = time.time() - start_time
        logger.info(
            "Simulator done: %d messages in %.1f s (%.0f msg/s), %d unflushed",
            message_count, elapsed,
            message_count / max(elapsed, 0.001),
            remaining,
        )


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    parser = argparse.ArgumentParser(description="PrimeEV Factory Simulator")
    parser.add_argument("--data-dir", default="data", help="Data directory (default: data)")
    parser.add_argument("--speed", type=float, default=100.0, help="Speed multiplier (default: 100x)")
    parser.add_argument("--max-messages", type=int, default=None, help="Max sensor messages to send")
    parser.add_argument("--no-production-events", action="store_true", help="Skip production event publishing")
    args = parser.parse_args()

    run_simulator(
        data_dir=args.data_dir,
        speed_multiplier=args.speed,
        max_messages=args.max_messages,
        emit_production_events=not args.no_production_events,
    )
