apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      server: clickhouse
      port: 8123
      username: default
      defaultDatabase: primeev_telemetry
      protocol: http
    editable: true
